server:
  port: 8900

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 
    username: 
    password: 


logging:
  config: classpath:logback.xml

mybatis:
  mapper-locations: classpath*:mapper/*.xml